### ISSUE TITLE
Documentation - Code

### ISSUE THREAD

**Issue by GeekyMonkey** [shibayan/azure-appservice-letsencrypt#7]
This looks very promising, but I haven't managed to get it working. The documentation in the readme is very sparse and I don't know what value to put into the curl command for "code".  A full example would help.  Even better would be step-by-step with pictures or a youtube video.

**Comment by shibayan** [comment]
@GeekyMonkey 

The `code` parameter is Azure Functions secret key. You can get using "Get Function URL" in Azure Portal.
https://markheath.net/post/managing-azure-function-keys

And since there was a problem with the previous release, please restart Azure Functions. The document is improving.

Thanks

**Comment by shibayan** [comment]
Fixed
